# Generated by Django 4.2.5 on 2023-09-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_tagline_freelancer_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
